[package]
name = "fuselage"
version = "0.1.0"
authors = ["Miles Granger <miles59923@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "^1", features = ["derive"] }
serde-value = "*"
csv = "^1"
derive_builder = "^0.7"
flate2 = "^1"
